// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-VUmrK4m3ZTFFIQullFWO5qRRFtbeMTo',
    appId: '1:568251685024:web:26f70274c4afaf5d93d1c5',
    messagingSenderId: '568251685024',
    projectId: 'whearther-dd8ec',
    authDomain: 'whearther-dd8ec.firebaseapp.com',
    storageBucket: 'whearther-dd8ec.firebasestorage.app',
    measurementId: 'G-2939N6N5XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnHiH42Bhc2bo2r8Mhpf6OeF1bxrN-14',
    appId: '1:568251685024:android:e66dc5adbd89cdd293d1c5',
    messagingSenderId: '568251685024',
    projectId: 'whearther-dd8ec',
    storageBucket: 'whearther-dd8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGL47pcck8BlRlBOM6hIwtlF7Z6A_QGHA',
    appId: '1:568251685024:ios:3566e62f2a2b3d0893d1c5',
    messagingSenderId: '568251685024',
    projectId: 'whearther-dd8ec',
    storageBucket: 'whearther-dd8ec.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGL47pcck8BlRlBOM6hIwtlF7Z6A_QGHA',
    appId: '1:568251685024:ios:3566e62f2a2b3d0893d1c5',
    messagingSenderId: '568251685024',
    projectId: 'whearther-dd8ec',
    storageBucket: 'whearther-dd8ec.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-VUmrK4m3ZTFFIQullFWO5qRRFtbeMTo',
    appId: '1:568251685024:web:d3b43d2ea9c5222b93d1c5',
    messagingSenderId: '568251685024',
    projectId: 'whearther-dd8ec',
    authDomain: 'whearther-dd8ec.firebaseapp.com',
    storageBucket: 'whearther-dd8ec.firebasestorage.app',
    measurementId: 'G-MFH0EDSNBH',
  );
}
